### ISSUE TITLE
Update npm package to include new commits

### ISSUE THREAD

**Issue by ejhayes** [justengland/phantomjs-lambda-pack#3]
Thanks for publishing this thing!

It appears that the [npm package](https://www.npmjs.com/package/phantomjs-lambda-pack) doesn't include this [commit](https://github.com/justengland/phantomjs-lambda-pack/commit/22c3318252be5ab22008572ef6b9e3298ff9f580).

Any way you can update it?

**Comment by arussel** [comment]
+1

**Comment by justengland** [comment]
I have updated NPM to 0.0.6 sorry about the delay.

**Comment by ejhayes** [comment]
Thanks @justengland !
