### ISSUE TITLE
How to skip install phantomjs-prebuilt@2.1.8

### ISSUE THREAD

**Issue by do-n-khanh** [justengland/phantomjs-lambda-pack#5]
Hi, I am new to phantomjs and lambda aws.
I am following your example and it works, but it takes 62 s to run on aws.
I guess it takes time because it needs to install phantomjs-prebuilt@2.1.8 everytime. How do I solve this problem?

When I ran on local using "serverless invoke local --function ktest", it shows me 
--------
pack:Install Phantom Called
pack:Install Phantom Called: IS HOSTED
shellSync: mkdir -p /tmp/phantom
pack:mkdirOut: 
shellSync: mkdir -p /tmp/.npm
pack:mkdir2Out: 
shellSync: npm install phantomjs-prebuilt@2.1.8
npm WARN saveError ENOENT: no such file or directory, open '/private/tmp/phantom/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/private/tmp/phantom/package.json'
npm WARN phantom No description
npm WARN phantom No repository field.
npm WARN phantom No README data
npm WARN phantom No license field.

pack:npmInstall: [[ 
> phantomjs-prebuilt@2.1.8 install /private/tmp/phantom/node_modules/phantomjs-prebuilt
> node install.js

PhantomJS not found on PATH
Download already available at /var/folders/5n/30h35bz50cdc1hf433nt_nx40000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip
Verified checksum of previously downloaded file
Extracting zip contents
Removing /private/tmp/phantom/node_modules/phantomjs-prebuilt/lib/phantom
Copying extracted folder /var/folders/5n/30h35bz50cdc1hf433nt_nx40000gn/T/phantomjs/phantomjs-2.1.1-macosx.zip-extract-1524833898970/phantomjs-2.1.1-macosx -> /private/tmp/phantom/node_modules/phantomjs-prebuilt/lib/phantom
Writing location.js file
Done. Phantomjs binary available at /private/tmp/phantom/node_modules/phantomjs-prebuilt/lib/phantom/bin/phantomjs
+ phantomjs-prebuilt@2.1.8
updated 1 package in 2.09s
 ]]

**Comment by justengland** [comment]
Take a look at my other project, it shows how to use a build server to preload the install.

https://github.com/justengland/phantom-lambda-template
